const productSet = [{
    image: ['/demoimg1.jpg','/demoimg0.jpg'],
    PublicationDate: 13062022,
    isDiscount: true,
    beforePrice: 85990,
    price: 74990,
    name: 'Pistola Llave de Impacto 320NM 1/2 - 2 Baterias 21V',
    materiales:[],
    alto:'20',
    ancho:'30',
    peso:'2',
    profundidad:'',
    diametro:'',
    cantidad:1,
    coloresDisponibles:[],
    marca: '',
    modelo:'',
    description: 'Pistola Llave de Impacto 320NM 1/2 - 2 Baterias 21V.',
    id: '0001ab',
    etiquetas: ['Herramientas'],
    category: 'Construcción',
    subcategories: ['Hogar y Muebles','Herramientas Eléctricas']
},{
    image: ['/demoimg2.png'],
    PublicationDate: 13062022,
    isDiscount: false,
    beforePrice: 0,
    price: 3990,
    name: 'Funda Para Cojin Terciopelo con Pompones 45x45cm',
    materiales:['Terciopelo'],
    alto:'45',
    ancho:'45',
    peso:'',
    profundidad:'',
    diametro:'',
    cantidad:1,
    coloresDisponibles:[],
    marca: '',
    modelo:'',
    description: 'Funda Para Cojín Terciopelo con Pompones 45x45cm Material: Terciopelo  Medidas: 45cm x 45cm. Cierre: Oculto.',
    id: '0002ab',
    category: 'Hogar y Muebles',
    subcategories: [],
    etiquetas: ['cojin','decoracion','fundas','terciopelo','hogar']
},{
    image: ['/demoimg3.jpeg'],
    PublicationDate: 13062022,    
    isDiscount: true,
    beforePrice: 165990,
    price: 129990,
    name: 'Banqueta Alejandria Color Gris',
    materiales:['Madera pino seco','Espuma poliuretano','Tela Felpa lisa'],
    alto:'60',
    ancho:'30',
    peso:'',
    profundidad:'45',
    diametro:'30',
    cantidad:'',
    coloresDisponibles:['Gris'],
    marca: 'Tapiceria Moderna',
    modelo:'Alejandria',
    description:'Marca: Tapiceria Moderna Modelo: Alejandria Tipo: Banquetas Hecho en: Chile  ',
    id: '0003ab',
    category: 'Hogar y Muebles',
    subcategories: [],
    etiquetas: []
},{
    image: ['/demoimg4.jpg'],
    PublicationDate: 13062022,
    isDiscount: false,
    beforePrice: 0,
    price: 235000,
    name: 'Intercooler Top Mount Impreza Wrx 02 07 + Y Pipe',
    materiales:[],
    alto:'',
    ancho:'',
    peso:'',
    profundidad:'',
    diametro:'',
    cantidad:'',
    coloresDisponibles:[],
    marca: '',
    modelo:'',
    description:'INTERCOOLER TOP MOUNT IMPREZA WRX 2002 2003 2004 2005 2006 2007 + Y PIPE',
    id: '0004ab',
    etiquetas: [' automotrices','impreza','intercooler','repuestos','subaru','topmount','wrx','ypipe'],
    category: 'Automóvil',
    subcategories: []
},{
    image: ['/demoimg5.jpeg'],
    PublicationDate: 13062022,
    isDiscount: false,
    beforePrice: 0,
    price: 8990,
    name: 'Alisador Vaporizador',
    materiales:[],
    alto:'',
    ancho:'34',
    peso:'',
    profundidad:'',
    diametro:'',
    cantidad:'',
    marca: '',
    modelo:'',
    coloresDisponibles:[],
    description:'Calienta de manera rápida sin dañar, aplicable a todo tipo de cabello ya sea húmedo o en seco. Especificaciones:Plancha profesional.Luz de indicador.Placas de aluminio con recubrimiento de cerámica no se pega al cabello ni lo daña.Temperatura graduable a 170/190/210/230cºTamaño 34cm aprox',
    id: '0005ab',
    etiquetas: ['Alisadora','cabello','Cuidado del Cabello','vapor'],
    category: 'Belleza y Cuidado Personal',
    subcategories: []
},{
    image: ['/demoimg6.jpg'],
    PublicationDate: 13062022,
    isDiscount: false,
    beforePrice: 0,
    price: 200000,
    name: 'Notebook Dell',
    materiales:[],
    largo:'',
    ancho:'',
    alto:'',
    peso:'',
    diametro:'',
    unidades:'',
    coloresDisponibles:[],
    marca: 'DELL',
    modelo:'inspiron 14-3467',
    description:'Notebook DELL inspiron 14-3467. Estoy haciendo cambio de notebook porque necesito uno más pequeño. Hace menos de 1 año, se le hizo cambio de disco duro a un disco sólido. Cargador nuevo (4 meses de uso) Procesador: INTEL® CORE? i3 6006U @ 2.0 GHz Memoria Ram: 6GB Gráficos: INTEL® HD Graphics 520 Pantalla: 14″ HD ',
    id: '0006ab',
    etiquetas: ['Notebook Dell inspirion'],
    category: 'Tecnología',
    subcategories: []
},{
    image: ['/demoimg7.jpeg'],
    PublicationDate: 13062022,
    isDiscount: true,
    beforePrice: 24990,
    price: 19990,
    name: 'Balanzas Mecánica Baño 120kg Marcas Terraillon Y Cotidiana.',
    materiales:['metal'],
    largo:'26',
    ancho:'26',
    alto:'5',
    peso:'',
    diametro:'',
    unidades:1,
    coloresDisponibles:['azul','blanco'],
    marca: 'Terraillon',
    modelo:'',
    description:'Modelo T61 Diseño Compacto. Capacidad Max Usuario 120 Kgs. Esfera Numérica. Plataforma Metálica, antideslizante y blanda.',
    marca: ' Terraillon',
    modelo:'Modelo T61',
    id: '0007ab',
    etiquetas: [],
    category: 'Deportes y Fitness',
    subcategories: ['Belleza y Cuidado Personal']
},{
    image: ['/demoimg8.png','/demoimg81.jpg','/demoimg82.jpg'],
    PublicationDate: 13062022,
    isDiscount: true,
    beforePrice: 450000,
    price: 410000,
    name: 'Receiver Yamaha Rx-va465 5.1. Poco Uso, Excelente.',
    materiales:[],
    largo:'30',
    ancho:'40',
    alto:'12',
    peso:'3.5',
    diametro:'',
    unidades:'',
    coloresDisponibles:['negro'],
    marca: 'Yamaha',
    modelo:'Rx-va465',
    description:'Receiver Yamaha Rx-va465 5.1. Poco Uso, Excelente. Oportunidad Equipo Yamaha en perfecto estado, con sus accesorios. Se vende por no uso. También tengo para ofrecer 5 parlantes Sony y un SubWoofer genérico a la venta. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab odit, maxime molestiae id culpa unde, fuga iste accusamus labore, inventore corrupti sint qui aliquam consequuntur vitae maiores porro sed sunt?',
    id: '0008ab',
    etiquetas: ['oferta','Precios Bajos','Receiver','Yamaha'],
    category: 'Electrónica,Audio y Video',
    subcategories: ['Home Theater','Receiver','Audio 5.1']
},{
    image: ['/demoimg9.jpg'],
    PublicationDate: 13062022,
    isDiscount: true,
    beforePrice: 280000,
    price: 260000,
    name: 'Vestido de novia Importado',
    materiales:[],
    largo:'',
    ancho:'',
    alto:'',
    peso:'',
    diametro:'',
    unidades:'',
    coloresDisponibles:[],
    marca: '',
    modelo:'',
    description:'Se vende lindo Vestido de Novia Importado Strapless Color Ivoy, de tala Crep yoryet, estilo romántico',
    id: '0009ab',
    etiquetas: ['Vestido de Novia','strapless','color Ivory'],
    category: 'Vestuario y Calzado',
    subcategories: []
},
{
    image: ['/demoimg10.jpeg'],
    PublicationDate: 13062022,
    isDiscount: true,
    beforePrice: 19900,
    price: 17900,
    name: 'Pack 10 cajas 25x25x25 Doble altura',
    materiales:['cartulina duplex'],
    largo:'25',
    ancho:'25',
    alto:'25',
    peso:'',
    diametro:'',
    unidades:'10',
    coloresDisponibles:[],
    marca: '',
    modelo:'',
    description:'Se Pack 10 cajas 25x25x25 Con Visor Nuestras cajas son totalmente AUTOARMABLES. Todas se abren por la parte delantera para mayor comodidad. Fabricadas en Cartulina Reverso Blanco DUPLEX de 350grs Super resistentes y fuertes También fabricamos en otras medidasvende lindo Vestido de Novia Importado Strapless Color Ivoy, de tala Crep yoryet, estilo romántico',
    id: '0010ab',
    etiquetas: ['Packaging'],
    category: 'Cotillón y Fiestas',
    subcategories: []
},
{
    image: ['/demoimg11.jpg'],
    PublicationDate: 13062022,
    isDiscount: true,
    beforePrice: 280000,
    price: 250000,
    name: 'Bicicleta Eléctrica Plegable',
    materiales:[],
    largo:'',
    ancho:'',
    alto:'',
    peso:'',
    diametro:'',
    unidades:'',
    coloresDisponibles:[],
    marca: '',
    modelo:'',
    description:'Bicicleta Eléctrica Plegable',
    id: '0011ab',
    etiquetas: [],
    category: 'Juegos Infantiles',
    subcategories: ['Bicicletas']
}
]

export default productSet

