const productSet = [{
    image : './demoimg1.jpg',
    isDiscount: true,
    beforePrice : 85990,
    price : 74990,
    name : 'Pistola Llave de Impacto 320NM 1/2 - 2 Baterias 21V',
    description : '',
    id : '0001ab',
    categories : ['Construcción','Hogar y Muebles']
},{
    image: './demoimg2.png',
    isDiscount: false,
    beforePrice: 0,
    price: 3990,
    name: 'Funda Para Cojin Terciopelo con Pompones 45x45cm',
    materiales:['Terciopelo'],
    alto:45,
    ancho:45,
    peso:0,
    profundidad:0,
    diametro:0,
    cantidad:1,
    description: 'Funda Para Cojín Terciopelo con Pompones 45x45cm Material: Terciopelo  Medidas: 45cm x 45cm. Cierre: Oculto.',
    id: '0002ab',
    etiquetas: ['Hogar y Muebles'],
    categories: ['cojin','decoracion','fundas','terciopelo','hogar']
},{
    image: './demoimg3.jpeg',
    isDiscount: true,
    beforePrice: 165990,
    price: 129990,
    name: 'Banqueta Alejandria Color Gris',
    materiales:['Madera pino seco','Espuma poliuretano','Tela Felpa lisa'],
    alto:60,
    ancho:30,
    peso:0,
    profundidad:45,
    diametro:30,
    cantidad:1,
    description:'Marca: Tapiceria Moderna Modelo: Alejandria Tipo: Banquetas Hecho en: Chile  ',
    id: '0003ab',
    etiquetas: ['Hogar y Muebles'],
    categories: []
},{
    image: './demoimg4.jpg',
    isDiscount: false,
    beforePrice: 0,
    price: 235000,
    name: 'Intercooler Top Mount Impreza Wrx 02 07 + Y Pipe',
    materiales:[],
    alto:0,
    ancho:0,
    peso:0,
    profundidad:0,
    diametro:0,
    cantidad:1,
    description:'INTERCOOLER TOP MOUNT IMPREZA WRX 2002 2003 2004 2005 2006 2007 + Y PIPE',
    id: '0004ab',
    etiquetas: [' automotrices','impreza','intercooler','repuestos','subaru','topmount','wrx','ypipe'],
    categories: ['Automóvil']
},{
    image: './demoimg5.jpeg',
    isDiscount: false,
    beforePrice: 0,
    price: 8990,
    name: 'Alisador Vaporizador',
    materiales:[],
    alto:0,
    ancho:34,
    peso:0,
    profundidad:0,
    diametro:0,
    cantidad:1,
    description:'Calienta de manera rápida sin dañar, aplicable a todo tipo de cabello ya sea húmedo o en seco. Especificaciones:Plancha profesional.Luz de indicador.Placas de aluminio con recubrimiento de cerámica no se pega al cabello ni lo daña.Temperatura graduable a 170/190/210/230cºTamaño 34cm aprox',
    id: '0005ab',
    etiquetas: ['Alisadora','cabello','Cuidado del Cabello','vapor'],
    categories: ['Belleza y Cuidado Personal']
},{
    image: './demoimg6.jpg',
    isDiscount: false,
    beforePrice: 0,
    price: 200000,
    name: 'Notebook Dell',
    materiales:[],
    alto:0,
    ancho:0,
    peso:0,
    profundidad:0,
    diametro:0,
    cantidad:1,
    description:'Notebook DELL inspiron 14-3467. Estoy haciendo cambio de notebook porque necesito uno más pequeño. Hace menos de 1 año, se le hizo cambio de disco duro a un disco sólido. Cargador nuevo (4 meses de uso) Procesador: INTEL® CORE? i3 6006U @ 2.0 GHz Memoria Ram: 6GB Gráficos: INTEL® HD Graphics 520 Pantalla: 14″ HD ',
    id: '0006ab',
    etiquetas: ['Notebook Dell inspirion',],
    categories: ['Tecnología']
},{
    image: './demoimg7.jpeg',
    isDiscount: true,
    beforePrice: 24990,
    price: 19990,
    name: 'Balanzas Mecánica Baño 120kg Marcas Terraillon Y Cotidiana.',
    materiales:['metal'],
    largo:26,
    ancho:26,
    alto:5,
    peso:0,
    diametro:0,
    unidades:1,
    coloresDisponibles:['azul','blanco'],
    description:'Modelo T61 Diseño Compacto. Capacidad Max Usuario 120 Kgs. Esfera Numérica. Plataforma Metálica, antideslizante y blanda.',
    id: '0007ab',
    etiquetas: [],
    categories: ['Deportes y Fitness','Belleza y Cuidado Personal']
},{
    image: './demoimg8.png',
    isDiscount: true,
    beforePrice: 450000,
    price: 410000,
    name: 'Receiver Yamaha Rx-va465 5.1. Poco Uso, Excelente.',
    materiales:[],
    largo:0,
    ancho:0,
    alto:0,
    peso:0,
    diametro:0,
    unidades:0,
    coloresDisponibles:['negro'],
    description:'Receiver Yamaha Rx-va465 5.1. Poco Uso, Excelente.',
    id: '0008ab',
    etiquetas: ['oferta','Precios Bajos','Receiver','Yamaha'],
    categories: ['Electrónica,Audio y Video']
},{
    image: './demoimg.jpg',
    isDiscount: true,
    beforePrice: 85990,
    price: 74990,
    name: 'Pistola Llave de Impacto 320NM 1/2 - 2 Baterias 21V',
    description: '',
    id: '0009ab',
    categories: ['Construcción','Hogar y Muebles']
},
{
    image: './demoimg.jpg',
    isDiscount: true,
    beforePrice: 85990,
    price: 74990,
    name: 'Pistola Llave de Impacto 320NM 1/2 - 2 Baterias 21V',
    description: '',
    id: '0010ab',
    categories: ['Construcción','Hogar y Muebles']
},
{
    image: './demoimg.jpg',
    isDiscount: true,
    beforePrice: 85990,
    price: 74990,
    name: 'Pistola Llave de Impacto 320NM 1/2 - 2 Baterias 21V',
    description: '',
    id: '0011ab',
    categories: ['Construcción','Hogar y Muebles']
}
]

export default productSet

